[package]
name = "torrent"
edition = "2024"

[features]
default = ["into_domain"]
into_domain = ["dep:domain"]

[dependencies]
reqwest = "0.12.24"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
domain = { path = "../domain", optional = true }
