[package]
name = "torrent"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
domain = { path = "../domain" }
base64 = { workspace = true }
log = { workspace = true }
